### ISSUE TITLE
Add "Terms and Conditions" popup (?) panel in new proposal

### ISSUE THREAD

**Issue by jayv** [devoxx/cfp-speaker#20]

**Comment by stephanj** [comment]
Devoxx 2013 Speaker Consent Form

On behalf of myself and my company/organisation, ("Organisation") and in consideration of my participation in the Event, I grant Devoxx (and its designated contractors), and its subsidiaries and affiliates under common control ("Devoxx") the following permissions in connection with Devoxx 2013, which are scheduled to take place November 11-15, 2013 (the "Event"):

Permission to use my name, biographic material, likeness, and portrait (hereinafter collectively referred to as my "Likeness") for the purpose of publicising my presentation(s) at/participation in the Event (my "Presentation").
Permission to make sound and visual recordings of my Presentation (the "Recordings").
Permission to use, copy, translate, reformat, broadcast, publish, and distribute all or parts of my Presentation, the Recordings, a transcript of the Recordings, and any presentation materials that I provide to Devoxx and use in connection with my Presentation (the "Presentation Materials"). This includes, without limitation, the right to distribute the Presentation Materials via streaming and download from the Parleys.com web site, and the right to distribute, broadcast and rebroadcast my Presentation as part of Event proceedings and archives that Devoxx makes available on its web site. Any such use must be in connection with the Event, and must not be misleading or reflect negatively on my Organisation or me.

I understand that neither my Organisation nor I will receive any compensation for granting these permissions. Devoxx is not granted any other permissions or rights with respect to my Likeness, my Presentation, the Recordings, or the Presentation Materials.

(1) I am the person who is accepting the invitation to present the session listed above;

(2) grant this permission and agree to the terms and conditions set forth above on behalf of my Organisation and myself;

(3) have authority to agree to such terms and conditions on behalf of my Organisation or co-speaker; and

(4) confirm that no further consents or permissions are required by Devoxx in order to use the Presentation Materials.
