### ISSUE TITLE
Using browser back button shows not logged in pages for X secs

### ISSUE THREAD

**Issue by daniel-deluca** [devoxx/cfp-speaker#40]
Scenario:
1: Log into the CFP web site
2: Click on the proposals  
3: Go down (bottom menu) and click on any of the Previous Edition links
4: wait for the Confluence page to load
5: click the back button on the browser
6: you see the non logged in page for X seconds before viewing again the page as logged in user.
X depends probably on the speed/initialization of the cloudbees instance.

The first try was 2 secs, then 0,5 sec but still visible/noticeable.

Browser user: Chrome  Version 27.0.1453.110
Platform: Mac OSX 10.8.3
Date/Time: 2013-06-06 18:45

**Comment by jayv** [comment]
That's expected behaviour in a single page JS app, navigating to "a" page (here caused by the back button) initializes the page again, starts the app, renders the anonymous page, needs to log you in again (async), render the logged in page, ... It's not cloudbees per se on the frontend part, although you could have hit a sleeping cloudbees backend cfp instance, so that the login request took a while to respond.

**Comment by daniel-deluca** [comment]
OK
